### PR TITLE
Minor updates following the migration of the repositories

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by Ladicek** [comment]
I already have all these changes locally, so this wasn't really required :-)

I'll check after the release of all the boosters is done.

**Comment by sberyozkin** [comment]
Np at all, took me virtually 5 mins, I just noticed the generate_licenses.sh had some old names following your IRC ping. Will close for now - please follow up later on with a new one or reopen this one, whatever is simpler for you :-)

**Comment by Ladicek** [comment]
I will check, maybe this is all that I had to change, in which case it will be simpler to just merge your PR :-)

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Turns out the changes in this PR were identical to the changes I made locally :-) So I added one more commit to improve `each.sh` and merged. Thanks!

**Pull request merged**
